data:
  dataset:
    name: races.dataset
    samples: 4044
    type: private
  datasetLoadOption: batch
  kfold: 1
  mapping:
    name:
      options:
        Augmentation: false
        Height: '30'
        Normalization: true
        Resize: true
        Scaling: 1
        Width: '30'
        height_shift_range: 0
        horizontal_flip: false
        pretrained: None
        rotation_range: 0
        shear_range: 0
        vertical_flip: false
        width_shift_range: 0
      port: InputPort0
      shape: ''
      type: Image
    rate:
      options: {}
      port: OutputPort0
      shape: ''
      type: Categorical
  numPorts: 1
  samples:
    split: 1
    test: 0
    training: 3235
    validation: 808
  shuffle: true
model:
  connections:
  - source: BatchNormalization_1
    target: Conv2D_1
  - source: Dense_1
    target: Dropout_3
  - source: Dropout_2
    target: Flatten_1
  - source: Flatten_1
    target: Dense_1
  - source: MaxPooling2D_2
    target: Dropout_2
  - source: Conv2D_3
    target: MaxPooling2D_2
  - source: Dense_2
    target: Output_1
  - source: Dropout_3
    target: Dense_2
  - source: Dropout_1
    target: Conv2D_2
  - source: Conv2D_2
    target: Conv2D_3
  - source: Conv2D_1
    target: Conv2D_4
  - source: MaxPooling2D_1
    target: Dropout_1
  - source: Conv2D_4
    target: MaxPooling2D_1
  - source: Input_1
    target: BatchNormalization_1
  layers:
  - args: {}
    class: Input
    name: Input_1
    x: 151
    y: 64
  - args:
      activation: relu
      filters: '32'
      kernel_size: 3
      padding: same
    class: Conv2D
    name: Conv2D_1
    x: 146
    y: 287
  - args:
      pool_size: (2,2)
    class: MaxPooling2D
    name: MaxPooling2D_1
    x: 156
    y: 508
  - args:
      rate: '0.25'
    class: Dropout
    name: Dropout_1
    x: 147
    y: 620
  - args:
      activation: relu
      filters: '64'
      kernel_size: 3
      padding: same
    class: Conv2D
    name: Conv2D_2
    x: 522
    y: 181
  - args:
      activation: relu
      filters: '64'
      kernel_size: 3
    class: Conv2D
    name: Conv2D_3
    x: 523
    y: 324
  - args:
      pool_size: (2,2)
    class: MaxPooling2D
    name: MaxPooling2D_2
    x: 523
    y: 480
  - args:
      rate: '0.25'
    class: Dropout
    name: Dropout_2
    x: 524
    y: 621
  - args: {}
    class: Flatten
    name: Flatten_1
    x: 898
    y: 66
  - args:
      activation: relu
      units: '512'
    class: Dense
    name: Dense_1
    x: 899
    y: 188
  - args:
      rate: '0.5'
    class: Dropout
    name: Dropout_3
    x: 899
    y: 324
  - args:
      activation: softmax
      units: '6'
    class: Dense
    name: Dense_2
    x: 901
    y: 476
  - args: {}
    class: Output
    name: Output_1
    x: 901
    y: 615
  - args:
      activation: relu
      filters: '32'
      kernel_size: '3'
    class: Conv2D
    name: Conv2D_4
    x: 157
    y: 402
  - args: {}
    class: BatchNormalization
    name: BatchNormalization_1
    x: 144
    y: 174
params:
  advance_params: true
  batch_size: '32'
  is_custom_loss: false
  loss_func: categorical_crossentropy
  num_epoch: 35
  optimizer:
    decay: 1e-6
    momentum: '0.9'
    name: SGD
    nesterov: true
project: faces&races
